name: Run Script
on: [push,workflow_dispatch]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install axios
      - run: npm install path
      - run: node main.js